(function(){
  'use strict';
  const $=id=>document.getElementById(id); const client=new SmallTalkMCPClient();
  let project='default', selected=null, rooms=[];
  function status(text,error){$('status').textContent=text;$('status').className=error?'error':'status'}
  function renderRooms(){const root=$('roomList');root.innerHTML='';rooms.forEach(r=>{const b=document.createElement('button');b.className='room'+(selected===r.room_id?' active':'');b.textContent=r.name||r.room_id;b.onclick=()=>{selected=r.room_id;renderRooms();loadArticles()};root.appendChild(b)})}
  async function loadArticles(){if(!selected)return; $('roomTitle').textContent=(rooms.find(r=>r.room_id===selected)?.name||selected)+' · 文章';$('articleList').className='empty';$('articleList').textContent='載入中...';try{const data=await client.call('smalltalk_list_articles',{project_id:project,room_id:selected,limit:50,simple:false});const list=Array.isArray(data)?data:(data.articles||[]);const root=$('articleList');root.innerHTML='';root.className='';if(!list.length){root.className='empty';root.textContent='目前沒有文章';return}list.forEach(a=>{const el=document.createElement('article');el.className='article';const title=document.createElement('h3');title.textContent=a.title||a.article_id||'未命名文章';const meta=document.createElement('div');meta.className='muted';meta.textContent=[a.author_id||a.author||'',a.updated_at||a.updatedAt||a.started_at||''].filter(Boolean).join(' · ');const body=document.createElement('div');body.className='body';body.textContent=a.message||a.text||a.root_message||a.rootMessage||'';el.append(title,meta,body);root.appendChild(el)})}catch(e){$('articleList').className='error';$('articleList').textContent=e.message||String(e)}}
  async function load(){try{await client.connect();const data=await client.call('smalltalk_list_rooms',{project_id:project});rooms=Array.isArray(data)?data:(data.rooms||[]);selected=selected&&rooms.some(r=>r.room_id===selected)?selected:(rooms[0]?.room_id||null);renderRooms();if(selected)await loadArticles();else{$('articleList').textContent='目前沒有公開房間'}status('Guest 瀏覽模式 · '+rooms.length+' 個房間')}catch(e){status(e.message||String(e),true)}}
  $('refresh').onclick=()=>load(); load();
})();
